services:
  - type: web
    name: smartstock-cloud
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        value: smartstock_secret_key_prod_2025
      - key: NODE_ENV
        value: production
    disk:
      name: smartstock-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
